language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5


sudo: false
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

install:
  - travis_retry pip install tox

script:
  - git describe --tags
  - tox

